name: Compile and Run C Programs

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install GCC Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc

    - name: Compile and Run C Programs
      run: |
        for file in *.c; do
          echo "Compiling $file"
          gcc "$file" -o "${file%.c}.out"
          echo "Running ${file%.c}.out"
          ./"${file%.c}.out"
          echo "-----------------------------------"
        done
