name: Compile and Run C Programs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up GCC
        run: sudo apt-get install gcc
      - name: Compile C programs
        run: gcc *.c -o output_programs
      - name: Run programs
        run: ./output_programs
